"""Update post for polarsteps

Revision ID: 3eac5e5e23d8
Revises: 0de3d3c9e888
Create Date: 2025-05-08 16:24:21.783629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eac5e5e23d8'
down_revision = '0de3d3c9e888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('long', sa.Float(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('long')
        batch_op.drop_column('lat')
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###
