"""empty message

Revision ID: 936892ad00f6
Revises: a39d5b2a96a6
Create Date: 2025-03-12 13:47:49.833255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936892ad00f6'
down_revision = 'a39d5b2a96a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('post_uesr_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('uesr_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uesr_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_uesr_id_fkey', 'user', ['uesr_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
